### ISSUE TITLE
Support CUDA 13 / RTX 5070 Ti

### ISSUE THREAD

**Issue by Toluwani5778** [remsky/Kokoro-FastAPI#443]
Hi Kokoro Team,

Currently, the Docker image uses CUDA 12.8. My RTX 5070 Ti requires CUDA 13, and PyTorch fails to load models with CUDA errors. 
I tested a modified Dockerfile based on CUDA 13.0.1 + cuDNN and installing PyTorch with CUDA 13 wheels, and the model works correctly on newer GPUs.

Proposed changes:
- Update base image: nvcr.io/nvidia/cuda:13.0.1-cudnn-devel-ubuntu24.04
- Ensure PyTorch installs the CUDA 13 wheel: pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu13

This allows support for the latest GPUs (like RTX 5070 Ti) while keeping compatibility with the existing stack.

Thank you!

The modified dockerfile found at
docker/gpu/Dockerfile

```dockerfile
# Use CUDA 13 base with cuDNN, Ubuntu 24.04
FROM --platform=$BUILDPLATFORM nvcr.io/nvidia/cuda:13.0.1-cudnn-devel-ubuntu24.04

# Enable universe repository and install dependencies
# Install dependencies
RUN apt-get update -y && \
    apt-get install -y software-properties-common && \
    add-apt-repository universe && \
    apt-get update -y && \
    apt-get install -y \
        python3 python3-venv python3-pip \
        espeak-ng espeak-ng-data \
        git libsndfile1 curl ffmpeg g++ cmake && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    mkdir -p /usr/share/espeak-ng-data && \
    ln -s /usr/lib/*/espeak-ng-data/* /usr/share/espeak-ng-data/ && \
    curl -LsSf https://astral.sh/uv/install.sh | sh && \
    mv /root/.local/bin/uv /usr/local/bin/ && \
    mv /root/.local/bin/uvx /usr/local/bin/ && \
    useradd -m -u 1001 appuser && \
    mkdir -p /app/api/src/models/v1_0 && \
    chown -R appuser:appuser /app

USER appuser
WORKDIR /app

# Copy dependency files
COPY --chown=appuser:appuser pyproject.toml ./pyproject.toml

# Install dependencies with GPU extras using system Python 3
RUN uv venv --python python3 && \
    uv sync --extra gpu --no-cache

# Copy project files including models
COPY --chown=appuser:appuser api ./api
COPY --chown=appuser:appuser web ./web
COPY --chown=appuser:appuser docker/scripts/ ./
RUN chmod +x ./entrypoint.sh

# Set environment variables
ENV PATH="/app/.venv/bin:$PATH" \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app:/app/api \
    UV_LINK_MODE=copy \
    USE_GPU=true \
    PHONEMIZER_ESPEAK_PATH=/usr/bin \
    PHONEMIZER_ESPEAK_DATA=/usr/share/espeak-ng-data \
    ESPEAK_DATA_PATH=/usr/share/espeak-ng-data \
    DEVICE="gpu"

ENV DOWNLOAD_MODEL=true

# Download model if enabled
RUN if [ "$DOWNLOAD_MODEL" = "true" ]; then \
    python download_model.py --output api/src/models/v1_0; \
    fi

# Run FastAPI server through entrypoint.sh
CMD ["./entrypoint.sh"]
```

**Comment by digitalassassins** [comment]
I posted on this before, you can manually change the dependencies in the Composer build file to pull newer versions of PyTorch & CUDA..

Might be worth testing with the newer PyTorch and CUDA versions on your machine/docker container, see if it still works:

https://github.com/remsky/Kokoro-FastAPI/issues/320

The Dev should think about adding an environment variable that has the PyTorch version and Cuda version.
Then we can just set an Env variable in our Docker Compose.. That way, we can tune the package to suit our needs from the main image without having to build all the different versions for each of our graphics cards.

The Entrypoint should check the PyTorch version in ENV against what was last installed and saved into a txt file or env file inside the container. If it differs, it then removes CUDA, PyTorch, and all dependencies using pip, then reinstalls the version stated in the Env file. 

- CUDA_INSTALL=13.0.1
- PYTORCH_INSTALL=cu13

This way, it can support all generations of NVIDIA cards with a simple ENV variable change.

**Comment by helmingsmusik2-cmd** [comment]
Hello, and help
Im one of those that sit with a 5070ti and now it seems the latest build was reverted again and no longer support my card (as described [here 26-05-15 ](https://github.com/remsky/Kokoro-FastAPI/blob/master/CHANGELOG.md). It refers to this very thread and to change manually, but the code in the files 'docker' and 'docker.optimised' does not match the above and I have tried several times to change according to above, but it wont work to install regardless.. I need help

Can someone please describe what rows and what to change manually, Im not a developer so try to be as clear as possible or point to a page where it is described. Id really appreciate it. 
I now run on CPU, due to an unlucky uninstall just the other day :(

Thanks

**Comment by JenniferHatches** [comment]
> Hello, and help Im one of those that sit with a 5070ti and now it seems the latest build was reverted again and no longer support my card (as described [here 26-05-15 ](https://github.com/remsky/Kokoro-FastAPI/blob/master/CHANGELOG.md). It refers to this very thread and to change manually, but the code in the files 'docker' and 'docker.optimised' does not match the above and I have tried several times to change according to above, but it wont work to install regardless.. I need help
> 
> Can someone please describe what rows and what to change manually, Im not a developer so try to be as clear as possible or point to a page where it is described. Id really appreciate it. I now run on CPU, due to an unlucky uninstall just the other day :(
> 
> Thanks

I did some changes to use python 3.12, the latest cuda version, etc.  See attached changed files.  Note:  I am unskilled and just hacked away until it worked for me

[koko-changes.zip](https://github.com/user-attachments/files/28196424/koko-changes.zip)

**Comment by remsky** [comment]
Hey @JenniferHatches @helmingsmusik2-cmd @digitalassassins 

Sorry for the rough patch on the blackwell cards. The default gpu prebuilt image is currently set for cu126 for widest compatibility (maxwell through to ada), and I'm adjusting the tagging to be more explicit/adaptable for different CUDA versions instead of the back and forth we've had on support PR's. 

I'm pushing the new release shortly which will add the prebuilt cu128 image, but in the meantime, the changes are currently on master, and uncommenting lines 10-12 in docker/gpu/docker-compose.yml:
```
args:
  GPU_EXTRA: gpu-cu128
  CUDA_VERSION: 12.8.1
```
and running
```
 docker compose -f docker/gpu/docker-compose.yml up --build
```

from the project root should run for Blackwell. As far as I'm aware, cu128 contains the sm_120 kernels which are what is needed for the newer cards. If it is still causing CUDA errors on the 50-series, let me know, I'm looking at adding the cu13 variant as well.

**Comment by JenniferHatches** [comment]
Nice, thanks!  First time i've been able to just build straight from the repo without messing with anything and have cuda working.

I do see these messages in the startup log:

kokoro-tts-1  | 05:36:35 AM | INFO     | kokoro_v1:66 | Model path: /app/api/src/models/v1_0/kokoro-v1_0.pth
kokoro-tts-1  | WARNING: Defaulting repo_id to hexgrad/Kokoro-82M. Pass repo_id='hexgrad/Kokoro-82M' to suppress this warning.
kokoro-tts-1  | /app/.venv/lib/python3.10/site-packages/torch/nn/modules/rnn.py:123: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.2 and num_layers=1
kokoro-tts-1  |   warnings.warn(
kokoro-tts-1  | /app/.venv/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:144: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
kokoro-tts-1  |   WeightNorm.apply(module, name, dim)

but it works fine.  Thanks, one less thing i have to tinker with constantly lol

**Comment by remsky** [comment]
Glad to hear it, feel free to reopen if anything else pops up. Those warnings shouldn't cause any issue, but I can look at suppressing them once I have a chance to check them over proper (coming from the base kokoro/pytorch modules)

**Comment by helmingsmusik2-cmd** [comment]
Hey both, 
No worries, 
I manage to solve it by running another built docker image from Rushyrush image (that was posted somewehere Isk know where) which did it for me, 

Anyhow, I appreciate the help and support.
The app is great. I just wish Kokoro had more voices..
many thanks
